<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
<meta name="format-detection" content="telephone=no" />
<title><?php echo isset($metaTitle) ? $metaTitle : 'Hệ thống nghe nhạc DJ hàng đầu Việt Nam' ?></title>
<?php if (false):?>
<meta name="title" content="<?php echo isset($metaTitle) ? $metaTitle : 'Hệ thống nghe nhạc DJ hàng đầu Việt Nam' ?>" />
<meta name="description" content="<?php echo pagesupport::getmetadesc() ?>" />
<meta name="keywords" content="<?php echo pagesupport::getmetakeyword(); ?>" />
<link rel="canonical" href="<?php echo pagesupport::getcanonical(); ?>" />
<meta property="og:url" content="<?php echo pagesupport::getcanonical(); ?>" />
<meta property="og:title" content="<?php echo isset($metaTitle) ? $metaTitle : 'Hệ thống nghe nhạc DJ hàng đầu Việt Nam' ?>" />
<meta property="og:description" content="<?php echo pagesupport::getmetadesc() ?>" />
<meta property="og:image" content="<?php echo pagesupport::getmetaimage(); ?>" />
<meta property="og:image:url" content="<?php echo pagesupport::getmetaimage(); ?>" />
<meta property="og:site_name" content="<?php echo $sitename ?>" />
<?php endif;?>
<meta property="og:type" content="website" />
<meta name="ROBOTS" content="index, follow" />
<link rel="stylesheet" href="/wap/css/style.css" type="text/css" />
<link rel="stylesheet" href="/wap/css/newstyle.css" type="text/css" />
<link rel="shortcut icon" type="image/x-icon" href="http://nhacdj.vn/images/icon/favicon.png" />
<script type="text/javascript" src="/wap/js/jquery.js"></script>
<script type="text/javascript" src="/wap/js/function.js"></script>
<script type="text/javascript" src="/wap/js/cookie.js"></script>