<div class="btn-group btn-group-justified">
	<?php if(empty($hideTopNavigation)):?>
		<?php 
			$categories = Category::find(array(
					"conditions" => array(
							"parentid" => "",
							"type" => array(
									'$in' => array("audio", "video")
							)
					),
					"fields" => array("name", "type"),
					"sort"   => array("_id" => -1)
			));
		?>
		<?php foreach ($categories as $value):?>
		<a class="btn btn-default <?php echo $value->type ? "" : "disabled"; ?>" href="<?php echo Helper::urlGenerate($value->name, $value->_id, "category") ?>" title="<?php echo $value->name; ?>"><i class="fa fa-headphones"></i> <?php echo $value->name; ?></a>
		<?php endforeach;?>
		</div>
		<?php if (isset($showBreadcrumbs) && $showBreadcrumbs === true) :?>
			<ol class="breadcrumb">
				<li itemtype="http://data-vocabulary.org/Breadcrumb" itemscope="">
					<a itemprop="url" href="<?php echo $siteurl ?>">
						<span itemprop="title">Trang chủ</span>
					</a>
				</li>
				<?php foreach ($breadcrumbs as $item) : ?>
				<li itemtype="http://data-vocabulary.org/Breadcrumb" itemscope="">
					<a itemprop="url" href="<?php echo $item['link'] ?>">
						<span itemprop="title"><?php echo $item['name'] ?></span>
					</a>
				</li>
				<?php endforeach; ?>
			</ol>
		<?php endif; ?>
	<?php endif;?>
<div class="clearfix"></div>