<h5>Đổi mật khẩu tài khoản</h5>
<?php if (strlen($alertContent)):?>
	<p><?php echo $alertContent; ?></p>
<?php endif;?>
<form class="form-horizontal" action="" method="post" role="form">
   <div class="form-group">
      <div class="col-sm">
         <input type="password" class="form-control" name="oldpass"  placeholder="Mật khẩu cũ">
      </div>
   </div>
   <div class="form-group">
      <div class="col-sm">
         <input type="password" class="form-control" name=newpass  placeholder="Mật khẩu mới">
      </div>
   </div> 
   <div class="form-group">
      <div class="col-sm">
         <input type="password" class="form-control" name="renewpass"  placeholder="Nhập lại mật khẩu mới">
      </div>
   </div>   
   <div class="form-group">
      <div class="col-sm">
         <button type="submit" class="btn btn-default">Chấp nhận</button>
      </div>
   </div>
</form>