<?php 
	$albumName = $album['name'];
	$albumId = $album['_id'];
?>
<div class="music-info">
    <h1><?php echo $albumName; ?></h1>

    <div class="song-info">
        <ul>
            <li><i class="fa fa-headphones"></i> Lượt nghe: <span><?php echo $album['view'] ?></span></li>
            <li><i class="fa fa-thumbs-up"></i> Like: <span><?php echo $album['liked'] ?></span> / Dislike: <span><?php echo $album['dislike'] ?></span></li>
            <li><i class="fa fa-calendar"></i> Đăng ngày: <span><?php echo date("d-m-Y", $album['datecreate']) ?></span></li>
            <li><i class="fa fa-music"></i> Thể loại:
                <?php foreach ($album['categoryList'] as $category):?>
                <?php 
                	$categoryName = $category->name;
                ?>
                <a title="<?php echo $categoryName; ?>" href="<?php echo Helper::urlGenerate($categoryName, $category->_id, 'album')?>"><?php echo $categoryName ?></a>, 
                <?php endforeach;?>
            </li>
        </ul>
    </div>
    <div class="user-avatar">
        <a title="<?php echo $album['name'] ?>" href="<?php echo Helper::urlGenerate($album['name'], $album['_id'], "album") ?>">
            <img width="75" height="100" src="<?php echo $album['priavatar'] ?>" alt="<?php echo $album['name'] ?>">
        </a>
    </div>
</div>

<div class="music-player">
    <div class="ios-player">
        <p>&nbsp;</p>
        <audio style="width:100%;" autobuffer="" preload="auto" loop="" autoplay="" controls="">
            <source type="audio/mpeg" src="<?php echo Helper::switchlink($album['song'][0]['link']) ?>"></source>
            <p>Trình duyệt của bạn không hỗ trợ nghe nhạc !</p>
        </audio>
        <ul id="playlist">
            <?php foreach ($mediaList as $media):?>
			<?php 
				$mediaName = $media->name;
				$mediaId = $media->_id;
				++$index;
			?>
            <li class="active">
                <a href="<?php echo Helper::switchlink($media->link)?>"><span>  <?php echo $index; ?>. </span>
                    <?php echo $mediaName; ?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
        <p>&nbsp;</p>
    </div>
    <script src="/wap/js/playlist.js" type="text/javascript"></script>


</div>

<div class="music-tracklist">
    <h4 class="block-title"><i class="fa fa-info-circle"></i> Thông tin album:</h4>

    <div class="" id="track-list">
       <?php echo $album['lyric']; ?>
    </div>
    <a href="javascript:void(0);" class="btn text-warning btn-sm btn-block no-display" id="show-more-tracklist"><i class="fa fa-caret-down"></i>
        Xem thêm</a>
    <a href="javascript:void(0);" class="btn text-warning btn-sm btn-block" id="show-less-tracklist"><i class="fa fa-caret-up"></i>
        Thu gọn</a>
</div>

