<?php $this->partial("partial/breadCrumbs") ?>

<div class="topic-top-cover clearfix">
    <img src="<?php echo $topicObj['pribg'];?>#" alt="<?php echo $topicObj['name'];?>" width="980" height="310" />
</div>
<div class="topic-content">
<div id="left-topic-column">
    <div id="top-content">
        <div class="top-topic-content clearfix">
            <div class="topic-cover">
                <div class="topic_thumbnail">
                    <a title="{$topicObj.name}" href="#">
                        <img src="<?php echo $topicObj['priavatar'];?>#" alt="<?php echo $topicObj['name'];?>" />
                    </a>
                </div>
            </div>
            <div class="topic-info">
                <h1><?php echo $topicObj['name'];?></h1>
                <div class="topic-stats">
                    <span><i class="fa fa-headphones"></i><?php echo $topicObj['view'];?> </span>
                    <span>|</span>
                    <span><i class="fa fa-calendar"></i><?php echo $topicObj['date'];?> </span>
                    
                </div>
                <h2><?php echo $topicObj['moretitle'];?></h2>
                <div class="action clearfix">
                    <a data-original-title="Thích chủ đề này" href="javascript:likearticle(<?php echo $topicObj['_id']?>, <?php echo $topicObj['usercreate']?>, 'topic')" rel="tooltip" title="" id="like-album" class="btn btn-small btn-default"><i class="fa fa-thumbs-up"></i> Thích </a>
                    <a data-original-title="Không thích chủ đề này" href="javascript:dislikearticle(<?php echo $topicObj['_id']?>, 'topic')" rel="tooltip" title="" id="dislike-album" class="btn btn-small btn-default"><i class="fa fa-thumbs-down"></i> Ko Thích</a>
                    <a rel="tooltip" data-original-title="Ẩn / hiện khung chia sẻ" class="btn btn-small btn-default" id="share-btn" href="#shareCode"  data-toggle="modal" role="button"><i class="fa fa-code"></i> Nhúng</a>
                    <div id="shareCode" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					    <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Ẩn</button>
					        <h3 id="myModalLabel">Chèn vào web / forum</h3>
					    </div>
					    <div class="modal-body">
					        <p>
					        <p>Click vào khung mã tương ứng rồi bấm Ctrl + C để copy Code:</p>
					        <div><span>Đường dẫn:</span> <input class="embed-input" type="text" value="<?php echo Helper::makeShortLink($topicObj['_id'], 'topic')?>" readonly="readonly" onclick="this.select();" /></div>
					        <div><span>Nhúng web:</span> <input class="embed-input" type="text" value="&lt;embed src=&quot;<?php echo Helper::makeShortEmbedLink($topicObj['_id'], 'topic')?>&quot; width=&quot;640&quot; height=&quot;390&quot; loop=&quot;true&quot; quality=&quot;high&quot; pluginspage=&quot;http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash&quot; /&gt;" readonly="readonly" onclick="this.select();" /></div>
					        <div><span>Nhúng forum:</span> <input class="embed-input" type="text" value="[FLASH]<?php echo Helper::makeShortEmbedLink($topicObj['_id'], 'topic')?>[/FLASH]" readonly="readonly" onclick="this.select();" /></div>
					        </p>
					    </div>
					    <div class="modal-footer">
					        <button class="btn" data-dismiss="modal" aria-hidden="true">Đóng lại</button>
					    </div>
					</div>
                </div>
            </div>
        </div>
        <div class="topic-content">
            <?php if (count($topicObj['song']) == 0) :?>
            <div class="no-song">Chủ đề này hiện chưa có bản nhạc nào. Vui lòng chọn chủ đề khác !</div>
            <?php else :?>
            <div id="my_mediaplayer"></div>
            
            <script type="text/javascript">
            $(function () {
                var isBackClick = false;
                var isFirstPlay = false;
                var pl = [];
                var elemPlayer = $("#list-topic-song .song-item .song-name .tovernone a");
                if (!history) history = window.history;
                elemPlayer.each(function () {
                    pl.push({
                        'file': $(this).attr('data-src'),
                        'title': $(this).attr('data-title'),
                        'mediaid': $(this).attr('data-id')
                    });
                });
                 var privateplayer = jwplayer('my_mediaplayer').setup({
                    flashplayer: "/web/js/plugin/jwplayer/player.swf",
                    //file: elemPlayer.first().attr('data-src'),
                    width: "100%",
                    height: "28",
                    autostart: false,
                    skin: "/web/js/plugin/jwplayer/skins/vi/vi.xml",
                    controlbar: 'bottom',
                    dock: 'false',
                    abouttext: "Nhac dj",
                    aboutlink: "__",
                    playlist: pl,
                    repeat: 'always',
                    events: {
                        onPlaylistItem: function (event) {
                            item = jwplayer().getPlaylistItem();
                            $("#song_" + item.mediaid).addClass('play-song').siblings().removeClass('play-song');
                            if (isBackClick == false )
                                history.pushState({index : item.index}, 'play_media_detail', '/<?php echo $_SERVER['HTTP_X_ORIGINAL_URL']?>?st=' + item.index);
                            if (isFirstPlay == true) {
                                history.replaceState({index : item.index}, 'play_media_detail', '/<?php echo $_SERVER['HTTP_X_ORIGINAL_URL']?>?st=' + item.index);
                                isFirstPlay =  false;
                                isBackClick = false;
                            }
                        },
                        onBuffer: function(event) {
                            $("#loading").show();
                        },
                        onError: function(event) {
                            $("#loading").hide();
                            alert("Bài hát này tạm thời không nghe được ! Bấm F5 để tải lại hoặc thông báo cho BQT nếu tình trạng vẫn tiếp diễn !");
                        },
                        onPlay: function() {
                            $("#loading").hide();
                        }
                    }

                });
                elemPlayer.click(function (e) {
                    e.preventDefault();
                    isBackClick = false;
                    privateplayer.playlistItem($(this).attr('data-index') - 1);
                });
                window.onpopstate = function (e) {
                    if (e.state != null) {
                        isBackClick = true;
                        privateplayer.playlistItem(e.state.index);
                    }

                }
                
                isBackClick = true;
                isFirstPlay = true;
                privateplayer.playlistItem(0);
                
            });
            </script>
                    
            <div id="wrap-listsong">
            <div id="list-topic-song" class="clearfix">
                <?php foreach ($topicObj['song'] as $index=>$song):?>
                <?php 
                	$songName = $song['name'];
                	$songId = $song['_id'];
                ?>
                <div class="song-item clear" id="song_<?php echo $song['_id']; ?>">
                    <div class="song-name" >
                        <div class="left tovernone">
                            <input type="hidden" value="music" id="m_type9" /><?php echo $index + 1;?>. <a title="<?php echo $songName?>" data-src="<?php echo Helper::switchlink($song['link'])?>" data-title="<?php echo $songName; ?>" data-id="<?php echo $songId?>" data-index="<?php echo $index + 1; ?>" href="{$value.weblink}"><?php echo $songName; ?></a>
                        </div>
                    </div>
                    <div class="song-tool">
                        <a rel="tooltip" title="Tải bài hát này" href="{function=" linksupport::makedownload($value.name,$value._id)"}" target="_blank"><i class="fa fa-cloud-download"></i></a>
                        <a rel="tooltip" title="Nghe riêng bài hát này" href="{function=" linksupport::makemedia($value.name,$value._id)"}" target="_blank"><i class="fa fa-play-circle"></i></a>
                        <a rel="tooltip" title="Thêm bài hát này vào Playlist" class="addPlaylist-btn" href="javascript:void(0);" onclick="showAddPlaylist(<?php echo $song['_id']; ?>)"><i class="fa fa-plus-square"></i></a>
                    </div>
                </div>
                <?php endforeach;?>
            </div>
            </div>
            <?php endif; ?>
        </div>    
        
        <?php if (count($topicObj['listTag'])): ?>
        <div class="seperator-line1 clearfix"></div>
        <div class="seperator-line2"></div>
        <div class="mediainfo-padding">
            <b><i class="fa fa-tags"></i> Tags:</b>
            <div class="tag-cloud" style="overflow: hidden; width: auto; height: auto;">
                <ul>
                    <?php foreach ($topicObj['listTag'] as $tag):?>
                    <li><a href="<?php echo Helper::makeTagLink($tag['name'], $tag['_id'])?>" title="<?php echo $tag['name']?>" target="_blank"><span></span><?php echo $tag['name'] ?></a></li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
        <?php endif;?>
        <div>&nbsp;</div>    
    </div>
    
    <div id="related-col">
        <div class="col-bit clearfix">
            <h3 class="title">Chủ đề ngẫu nhiên</h3>
            <div class="col-content">
                <ul class="related">
                    <?php foreach ($otherTopic as $topic):?>
                    <li>
                        <a href="<?php echo Helper::makeTopicLink($topic['name'], $topic['_id'])?>" title="<?php echo $topic['name'];?>">
                            <img src="<?php echo $topic['priavatar'];?>#" />
                            <span class="icon-circle-play"><i class="fa fa-play-circle"></i></span>
                            <div class="topic-name"><?php echo $topic['name'];?></div>
                            <div class="item-mask"></div>
                        </a>
                    </li>
                    <?php endforeach;?>
                </ul>
            </div>
            <div class="clearfix"></div>
            <p class="center"><a href="/chu-de" title="Xem thêm" class="btn btn-default btn-sm">&raquo; Xem thêm các chủ đề thú vị khác</a></p>
        </div>
    </div>
    
    <div class="comment-col clearfix">
        <?php $this->partial("partial/comment", array("data" => $topicObj, "type" => "topic")) ?>
    </div>
</div>
    
<div id="right-topic-column">
    <div class="ad-300x600"><a href="http://fptshop.com.vn"><img src="http://photofloodstudio.com/wp-content/uploads/2014/04/activefigure_banner_300x600_B.jpg" /></a></div>
    <div class="col-bit clearfix">
        <h3 class="title">Chủ đề nghe nhiều</h3>
        <div class="col-content">
            <ul class="related">
                <?php foreach ($referTopic as $topic):?>
                <li>
                    <a href="<?php echo Helper::makeTopicLink($topic['name'], $topic['_id'])?>" title="<?php echo $topic['name'];?>">
						<img src="<?php echo $topic['priavatar'];?>#" />
						<span class="icon-circle-play"><i class="fa fa-play-circle"></i></span>
						<div class="topic-name"><?php echo $topic['name'];?></div>
						<div class="item-mask"></div>
					</a>
                </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
</div>

<div id="loading">Đang tải nội dung. Vui lòng chờ...</div>

</div>