<div class="column-bit breadcrumbs">
    <div class="item" itemtype="http://data-vocabulary.org/Breadcrumb" itemscope="">
        <a itemprop="url" title="Trang chủ" href="/">
            <span itemprop="title">Trang chủ</span>
        </a>
    </div>
    <?php 
    	$controller = $this->router->getControllerName();
	    $action = $this->router->getActionName();

	    switch ($controller){
	    	case 'category':
	    		if (($parentData = $data->getParentData()) != false){
	    			$params['link'] = Helper::urlGenerate($parentData->name, $parentData->_id, "category");
	    			$params['text'] = $parentData->name;
	    			$aryBreadCrumbs[] = $params;
	    		}
	    		
	    		$params['link'] = Helper::urlGenerate($data->name, $data->_id, "category");
	    		$params['text'] = $data->name;
	    		$aryBreadCrumbs[] = $params;
	    		break;
	    		
	    	case 'music':
	    		if (($parentData = $data->getParentData()) != false){
	    			$params['link'] = Helper::urlGenerate($parentData->name, $parentData->_id, "category");
	    			$params['text'] = $parentData->name;
	    			$aryBreadCrumbs[] = $params;
	    		}
	    		
	    		$params['link'] = Helper::urlGenerate($data->name, $data->_id, "category");
	    		$params['text'] = $data->name;
	    		$aryBreadCrumbs[] = $params;
	    		break;
	    		
    		case 'video':
    			if (($parentData = $data->getParentData()) != false){
    				$params['link'] = Helper::urlGenerate($parentData->name, $parentData->_id, "category");
    				$params['text'] = $parentData->name;
    				$aryBreadCrumbs[] = $params;
    			}
    			 
    			$params['link'] = Helper::urlGenerate($data->name, $data->_id, "category");
    			$params['text'] = $data->name;
    			$aryBreadCrumbs[] = $params;
    			break;
	    }
	?>
	<?php if (count($aryBreadCrumbs)):?>
	<?php foreach ($aryBreadCrumbs as $value):?>
	<div class="item" itemtype="http://data-vocabulary.org/Breadcrumb" itemscope="">
	    <a itemprop="url" title="<?php echo $value['text']; ?>" href="<?php echo $value['link']; ?>">
	        <span itemprop="title"><?php echo $value['text']; ?></span>
	    </a>
	</div>
	<?php endforeach;?>
	<?php endif;?>
</div>