<?php 
	/**
	- Display paging for some page
	- $linkForPage: use to assign the desire link
	- $countTotal: the total number of element
	- $totalPageL: the total number of page
	 */

	$pageNumber = $this->request->getQuery("p", int, 1);
	
	$url = $this->request->getQuery("_url");
?>
<?php if ($pageTotal > 0):?>
    <div class="pagination">
        <?php if ($pageNumber > 1):?>
        <a class="page" href="<?php echo $url; ?>?p=1">Đầu</a>
        <a class="page" href="<?php echo $url; ?>?p=<?php echo $pageNumber - 1; ?>"><?php echo $pageNumber - 1; ?></a>
        <?php endif;?>
        <a class="page active" href="<?php echo $url; ?>?p=<?php echo $pageNumber; ?>"><?php echo $pageNumber; ?></a>
        <?php if ($pageNumber < $pageTotal):?>
        <a class="page" href="<?php echo $url; ?>?p=<?php echo $pageNumber + 1; ?>"><?php echo $pageNumber + 1; ?></a>
        <a class="page" href="<?php echo $url; ?>?p=<?php echo $pageTotal; ?>">Cuối</a>
        <?php endif;?>
    </div>
    <div class="total-page">Tổng cộng <b><?php echo $totalNumber; ?></b> tác phẩm trong <b><?php echo $pageTotal; ?></b> trang</div>
<?php else :?>
    <div style="text-align: center">
        <p> <h3> Không có bài nào ! </h3></p>
    </div>
<?php endif;?>