<?php
	$type = isset($type) ? $type : 'audio';
	
	/**
	 * ca khuc chon loc
	 */
	$moduleTopMedia = ModuleTopMedia::find(array(
			"conditions" => array(
					'type' => "$type"
			)
	));
	
	$aryIds = array();
	foreach ($moduleTopMedia as $value){
		$aryIds[] = $value->itemid;
	}
	
	$mediaChoice = Media::find(array(
			array(
					'_id' => array(
							'$in' => $aryIds
					)
			),
			"sort" => array("like" => -1),
			array("_id", "name", "view", "like", "priavatar")
	)
	);
?>

<div id="right-listen-column">
    <div class="column-bit right-column">
        <div class="column-title">Ca khúc chọn lọc</div>
        <div class="column-content">
            <ul class="top-list">
            <?php $helper = new Helper();?>
            <?php foreach ($mediaChoice as $index => $value):?>
            <?php $name = $value->name;?>
            <li>
                <div class="top-icon top<?php echo $index+1?>"><?php echo $index+1?>.</div>
                <div class="top-right">
                    <h3><a href="<?php echo $helper->urlGenerate($name, $value->_id, $type)?>"
                           title="<?php echo $name;?>"><?php echo $name?></a></h3>
                </div>
                <br class="clear"/>
            </li>
            <?php endforeach;?>
        </ul>
        </div>
    </div>
    <div data-ng-app="myApp">
	    <div id="center-top-content" ng-controller="ViewTopMedia" style="margin-bottom: 10px">
	        <div class="tab-title">
	            <div class="tabs">
	                <div class= "tab" ng-class="{'active': sorttype=='view'}" id="top-listen-btn">
	                    <a ng-click="changeSort('view', 'top-listen-btn');">Top Nghe Nhiều</a>
	                </div>
	                <div class= "tab" ng-class="{'active': sorttype=='down'}" id="top-down-btn">
	                    <a ng-click="changeSort('down', 'top-down-btn');">Top Tải Nhiều</a>
	                </div>
	            </div>
	        </div>
	        <div class="tab-content" id="top-article">
	            <div class="choose-button selecttopviewmedia">
	                <a class="btn-choose left-btn active" ng-click="getTopArticle('w','audio','view',1);">Tuần</a>
	                <a class="btn-choose middle-btn" ng-click="getTopArticle('m','audio','view', 2);">Tháng</a>
	                <a class="btn-choose right-btn" ng-click="getTopArticle('y','audio','view',3);">Năm</a>
	            </div>
	
	            <ul class="top-list">
	                <li ng-repeat="media in listviewtopmedia">
	                    <div class="top-right">
	                        <span class="top-icon top{{media.index}}">{{media.index}}.</span>
	                        <h3><a href="{{media.intenetlink}}" title="{{media.name}}">{{media.name}}</a></h3>
	                    </div>
	                    <br class="clear"/>
	                </li>
	            </ul>
	            <div class="center top-viewmore-btn"><a href="bang-xep-hang-audio-w" title="Xem thêm"><b>&raquo; Xem thêm</b></a></div>
	        </div>
	    </div>
	    <!-- Begin: video right slidebar -->
    	<div class="right-bottom-content" ng-controller="ViewTopMediaWithImage"  ng-init="getTopMedia('<?php echo $type; ?>','w', 1)">
            <div class="tab-title">
                <div class="tabs">
                    <div  class="tab" ng-class="{'active': sorttype=='view'}" id="btn-video-view-choose">
                        <a ng-click="changeSort('video','view');">
                            <?php echo Helper::getTitle($type); ?> xem nhiều
                        </a>
                    </div>
                </div>
            </div>
            <div class="tab-content">
            <div id="news-choose" class="choose-button selecttopothermedia">
                <a class="btn-choose left-btn active" ng-click="getTopMedia('video','w', 1);">Tuần</a>
                <a class="btn-choose middle-btn" ng-click="getTopMedia('video','m', 2);">Tháng</a>
                <a class="btn-choose right-btn" ng-click="getTopMedia('video','y', 3);">Năm</a>
            </div>
            <div id="top-video-data">
                <div id="view-w-2" class="top-video-news" style="">
                    <div class="top-video-bit" ng-repeat="media in listMedia">
	                    <a href="{{media.intenetlink}}" class="top-video-thumb">
	                    	<img width="112" height="63" title="{{media.name}}" alt="Video thumb" src="{{media.priavatar}}#">
	                    	<span class="top-rank">{{media.index}}</span>
	                    </a>
	
	                    <div class="top-meta"><h3><a title="{{media.name}}" href="{{media.intenetlink}}">{{media.name}}</a></h3>
                            <p ng-if="sorttype=='view'">Lượt xem: {{media.view}}</p>
                            <p ng-if="sorttype=='down'">Lượt down: {{media.down}}</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div id="edit-playlist" ng-controller="EditPlaylist"></div>
    </div>
	</div>
</div>