<div aria-hidden="false" aria-labelledby="superComTitle" role="dialog" tabindex="-1" class="modal hide fade in" id="modal_like_unlike" style="display: none;">
    <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">Ẩn</button>
        <h3 id="superComTitle"></h3>
    </div>
    <div class="modal-body">
        <div id="tuoigiAlertContent">
            <span id="noneUser_like_dislike"></span>
            <ul>
            </ul>
        </div>
    </div>
    <div class="modal-footer">
        <button aria-hidden="true" data-dismiss="modal" class="btn btn-primary">Tắt đi</button>
    </div>
</div>

<script id="_tmplUserInfor" type="text/x-jquery-tmpl">
    <li>${index}.
        <img width="25" height="25" alt="Avatar" src="${priavatar}#" class="uavatar">
        <a href="${webLink}" target="_blank" melody="" bim="" title="DJ"> ${username}</a>
    </li>
</script>