<?php
	$aryStyles = array(
			1 => "danger",
			2 => "success",
			3 => "primary",
	);
?>
<div class="panel-group top-area" id="accordion">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                  <i class="fa fa-check"></i> Top đề cử
                </a>
              </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
              	<div class="panel-body">
	                <p class="center text-success">Các bài hát được đề cử nhiều nhất trong tuần bởi thành viên</p>
	                <div class="music-list">
	                <?php $i = 0; ?>
	                <?php foreach ($listMediaNomination as $value): ?>
	                <?php 
	                	$i++;
	                	$name = $value->name;
	                ?>
		                <div class="music-bit">
							<span class="label label-<?php echo isset($aryStyles[$i]) ? $aryStyles[$i] : "default"; ?>"><?php echo sprintf("%02s", $i) ?>.</span>
							<h3><a href="<?php echo Helper::urlGenerate($name, $value->_id, "audio") ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></h3>
							<div class="music-info info-top clearfix">
								<i class="fa fa-thumbs-up"></i> Được đề cử: <span><?php echo $value->totalVote; ?></span> lần
							</div>
						</div>
	                <?php endforeach; ?>
	
	                </div>
                </div>

                <div class="center cleafix bold margin-top-5"><a href="/nguoi-dung-binh-chon-audio-y" class="text-success" title="Xem thêm"><i class="fa fa-caret-down"></i> Xem thêm</a></div>

              </div>
            </div>
          </div>

          <div class="panel panel-warning">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                  <i class="fa fa-star"></i> Ca khúc chọn lọc
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
              <div class="panel-body">
                <p class="center text-warning">Các bài hát hay được chọn lọc bởi Ban Quản Trị</p>
                <div class="music-list">
                	<?php $i = 0; ?>
                    <?php foreach($mediaChoice as $value):?>
                    <?php 
                    	$i++;
                    	$name = $value->name; 
                    ?>
                    <div class="music-bit">
                        <span class="label label-<?php echo isset($aryStyles[$i]) ? $aryStyles[$i] : "default"; ?>"><?php echo sprintf("%02s", $i) ?>.</span>
                        <h3><a href="<?php echo Helper::urlGenerate($name, $value->_id, "audio") ?>" title="<?php echo $name ?>"><?php echo $name ?></a></h3>
                    </div>
                <?php endforeach;  ?>
                </div>
                <div class="center cleafix bold margin-top-5"><a href="/media-chon-loc-zmchoose_audio.html" class="text-warning" title="Xem thêm"><i class="fa fa-caret-down"></i> Xem thêm</a></div>

              </div>
            </div>
          </div>

          <div class="panel panel-primary">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                  <i class="fa fa-headphones"></i> Top nghe
                </a>
              </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
              <div class="panel-body">
                <p class="center text-primary">Các bài hát có lượt nghe nhiều nhất</p>

                <div class="btn-group btn-group-justified">
                  <a href="/bang-xep-hang-audio-w" class="btn btn-sm btn-primary disabled">Tuần</a>
                  <a href="/bang-xep-hang-audio-m" class="btn btn-sm btn-primary">Tháng</a>
                  <a href="/bang-xep-hang-audio-y" class="btn btn-sm btn-primary">Năm</a>
                </div>


                <div class="music-list">
                    <?php
                    	$moduleMediaView = ModuleMediaView::aggregate(array(
                    			array(
                    					'$match' => array(
                    							"type" => "audio",
                    							"dates.date" => array(
                    									'$lte' => time()
                    							)
                    					)
                    			),
                    			array('$unwind' => '$dates'),
                    			array(
                    					'$group' => array(
                    							'_id' => '$media',
                    							'count' => array(
                    									'$sum' => '$dates.view'
                    							)
                    					)
		                    	),
                    			array('$skip' => 0),
                    			array('$limit' => 10),
                    			array('$sort' => array(
                    					"count" => -1
                    				)
                    			)
                    	));
                    	
                    	$aryMediaDatas = array();
                        foreach($moduleMediaView['result'] as $value){
                            $aryMediaDatas[$value['_id']] = $value['count'];
                            $aryMediaIds[] = $value['_id'];
                        }
                        
                        $mediaList = Media::find(array(
                        		"conditions" => array(
                        				"_id" => array(
                        						'$in' => $aryMediaIds
                        				)
                        		),
                        		"fields" => array("name"),
                        		"sort" => array("_id" => 1)
                        ));
                        
                        if (count($mediaList)){
                        	$i = 0;
                        	foreach ($mediaList as $value){
                        		$i++;
                        		$name = $value->name;
                        		?>
                        		<div class="music-bit">
			                        <span class="label label-<?php echo isset($aryStyles[$i]) ? $aryStyles[$i] : "default"; ?>"><?php echo sprintf("%02s", $i) ?>.</span>
			                        <h3><a href="<?php echo Helper::urlGenerate($name, $value->_id, $value->type); ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></h3>
			                        <div class="music-info info-top clearfix">
			                            <i class="fa fa-headphones"></i> Được nghe: <span><?php echo $aryMediaDatas[$value->_id] ?></span> lần
			                        </div>
			                    </div>
                        		<?php 
                        	}
                        }
                    ?>

                    <div class="center cleafix bold margin-top-5"><a href="/top-media-tuan-ztop_w_audio.html" class="text-primary" title="Xem thêm"><i class="fa fa-caret-down"></i> Xem thêm</a></div>

              </div>
            </div>
          </div>

        </div>



        <h5>Danh sách các tác phẩm mới:</h5>
        <?php
        	$categoryIcon = array(
        			"audio" => "music-list",
        			"video" => "video-list no-margin"
        	);
        ?>
        
        <?php foreach ($baseCategoryList as $value):?>
        <div class="box-title">
            <h2 class="pull-left"><a href="<?php echo Helper::urlGenerate($value->name, $value->_id, "category"); ?>" title="<?php echo $value->name; ?>"><?php echo $value->name; ?></a></h2>
            <div class="clearfix"></div>
        </div>
        <?php $medias = $value->media;?>
        <?php foreach ($medias as $media):?>
        <?php
            $mediaId = $media->_id;
            $mediaName = $media->name;
            $mediaType = $media->type;
        ?>
        <div class="<?php echo isset($categoryIcon[$mediaType]) ? $categoryIcon[$mediaType] : "music-list"; ?>">
            <?php  if($mediaType == 'audio') : ?>
            <div class="music-bit">
                <div class="music-icon"><i class="fa fa-music"></i></div>
                <h3><a href="<?php echo Helper::urlGenerate($mediaName, $mediaId, "audio"); ?>" title="<?php echo $mediaName; ?>"><?php echo $mediaName; ?></a></h3>
                <div class="music-info clearfix">
                    <?php
                        $user = User::findFirst(array(
								"conditions" => array(
										"_id" => $media->usercreate
                        		),
                        		"fields" => array("name", "username")               		
                        ));
                    ?>
                    <i class="fa fa-user"></i> Đăng bởi: <a href="<?php echo Helper::makeUserLink($user->username, $user->_id)?>" title="<?php echo $user->name ?>"><?php echo $user->name ?></a> <span class="separator">/</span> <i class="fa fa-headphones"></i> <?php echo $media->view ?> <span class="separator">/</span> <i class="fa fa-download"></i> <?php echo $media->download ?> <?php if($media->ishot == 1) { ?> <span class="label label-danger label-margin">HOT</span> <?php } ?>  </div>
            </div>
            <?php elseif($mediaType == 'video') :?>
            <div class="video-bit">
                <a href="<?php echo Helper::urlGenerate($mediaName, $mediaId, "video"); ?>" title="<?php echo $mediaName; ?>"><img width="100" height="60" src="<?php echo $media->priavatar; ?>" alt="<?php echo $mediaName; ?>" /><i class="fa fa-youtube-play video-play-icon"></i></a>
                <h3><a href="<?php echo Helper::urlGenerate($mediaName, $mediaId, "video"); ?>" title="<?php echo $mediaName; ?>"><?php echo $mediaName; ?></a></h3>
                <div class="video-views"><i class="fa fa-eye"></i> Lượt xem: <?php echo $media->view ?></div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
        </div>
        <?php endforeach;?>
        <div class="view-more"><a class="btn btn-sm btn-warning btn-block" href="<?php echo Helper::urlGenerate($value->name, $value->_id, "category"); ?>" title="Xem thêm"><b><i class="fa fa-caret-down"></i> Xem thêm</b></a></div>
		<?php endforeach;?>
        <p></p>
