<div class="col-lg-12">
        <div class="row profile-head">
            <div class="profile-head-info">
                <div class="profile-avatar"><img class="imgavatar_big" src="<?php echo strlen($user->priavatar) <= 0 ? "/wap/images/01.png" : $user->priavatar; ?>" /></div>
                <div class="profile-name"><?php echo $user->username ?></div>
                <div class="profile-role"><?php echo $user->name ?></div>
            </div>
            
            <div class="profile-stats">
                <div class="profile-stats-bit"><p><?php echo number_format($userMediaCreatedCount); ?></p><span><i class="fa fa-music"></i> Bài</span></div>
                <div class="profile-stats-bit"><p><?php echo number_format($user->totalLike) ?></p><span><i class="fa fa-thumbs-up"></i> Like</span></div>
                <div class="profile-stats-bit"><p><?php echo number_format($user->totalFan) ?></p><span><i class="fa fa-user"></i> Fan</span></div>
            </div>
            
            <div class="profile-content">
                <ul class="nav nav-tabs" id="supercomTab">
                  <li class="active"><a href="#home" data-toggle="tab">Bài đã đăng</a></li>
                  <li><a href="#profile" data-toggle="tab">Thông tin</a></li>
                  <li><a href="#messages" data-toggle="tab">Tin nhắn</a></li>
                </ul>
                
                <div class="tab-content">
                  <div class="tab-pane active" id="home">
                                        <p class="center bold text-warning">Sắp xếp theo tiêu chí:</p>
                    <div class="btn-group btn-group-justified">
                      <a href="?sort=view" class="btn btn-sm btn-success <?php echo $sort == 'view' ? "" : "disabled"; ?>">Lượt xem</a>
                      <a href="?sort=like" class="btn btn-sm btn-success <?php echo $sort == 'like'? "" : "disabled"; ?>">Lượt like</a>
                      <a href="?sort=datecreate" class="btn btn-sm btn-success <?php echo $sort == 'datecreate'? "" :"disabled"; ?>">Ngày đăng</a>
                    </div>
                    
                    <p class="center margin-top-10">Bạn đang xem trang <b><?php echo $p ?></b></p>
                    
                    <div class="music-list">
                        <?php foreach($mediaList as $value): ?>
                        <?php 
		                	$name = $value->name;
		                ?>
                            <div class="music-bit">
                                <div class="music-icon"><i class="<?php echo $aryIcon[$value->type]; ?>">&nbsp;</i></div>
                                <h3><a href="<?php echo Helper::urlGenerate($name, $value->_id, $value->type); ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></h3>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <?php
                    if(count($mediaList)>0 && count($mediaList)>= $limit){ ?>
                    <div class="btn-group btn-group-justified"><a class="btn btn-default" href="?sort=<?php echo $sort ?>&p=<?php echo $p+1 ?>" title="Trang sau"><i class="fa fa-angle-right"></i> Trang sau</a></div>
                    <?php } 
                    else{ ?>         
                    <div class="btn-group btn-group-justified"><a class="btn btn-default" href="?sort=<?php echo $sort ?>&p=<?php echo $p-1 ?>" title="Trang trước"><i class="fa fa-angle-left"></i> Trang trước</a></div>
                    <?php } ?>           
                  </div>
                  
                  <div class="tab-pane" id="profile">
                    <div class="member-info alert alert-success">
                        <p><i class="fa fa-user"></i> Họ và tên: <strong><?php echo $user->name ?></strong></p>
                        <p><i class="fa fa-calendar"></i> Ngày sinh: <strong><?php $dob = $user->dob ? $user->dob :"0"; echo date("d-m-Y", $dob) ?></strong></p>
                        <p><i class="fa fa-smile-o"></i> Giới tính: <strong><?php $gender = $user->gender; if($gender == "1") echo "Nam"; else if($gender=="0") echo "Nữ"; else echo "Không xác định"; ?></strong></p>
                        <p><i class="fa fa-envelope"></i> Email: <strong><?php echo isset($user->email)? $user->email : "Đang cập nhật" ?></strong></p>
                        <p><i class="fa fa-building-o"></i> Địa chỉ: <strong><?php echo isset($user->address)? $user->address : "Đang cập nhật" ?></strong></p>
                        <p><i class="fa fa-phone"></i> Số điện thoại: <strong><?php echo isset($user->phone)? $user->phone : "Đang cập nhật" ?></strong></p>
                        <p><i class="fa fa-suitcase"></i> Nghề nghiệp: <strong><?php echo isset($user->job)? $user->job : "Đang cập nhật" ?></strong></p>
                        <p><i class="fa fa-gamepad"></i> Sở thích: <strong><?php echo isset($user->hobby)? $user->hobby : "Đang cập nhật" ?></strong></p>
                        <p><img src="<?php echo $user->priavatar ?>" width="100%" alt="Avatar" /></p>
                    </div>
                  </div>
                </div>
                
                <script>
                  $(function () {
                    $('#supercomTab a:first').tab('show')
                  })
                </script>
            </div>

        </div>  
    </div>