<?php 
	$aryTitles = array(
			"audio" => "bài hát",
			"video" => "video"
	)
?>

<p class="center text-success bold">Các <?php echo $aryTitles[$type]; ?> có lượt nghe nhiều nhất</p>
<div class="btn-group btn-group-justified">
  <a href="/bang-xep-hang-<?php echo $type; ?>-w" class="btn btn-sm btn-primary <?php echo $range == 'w' ? "" : "disabled" ?>">Tuần</a>
  <a href="/bang-xep-hang-<?php echo $type; ?>-m" class="btn btn-sm btn-primary <?php echo $range == 'm' ? "" : "disabled" ?>">Tháng</a>
  <a href="/bang-xep-hang-<?php echo $type; ?>-y" class="btn btn-sm btn-primary <?php echo $range == 'y' ? "" : "disabled" ?>">Năm</a>
</div>
<?php
	$aryStyles = array(
			1 => "danger",
			2 => "success",
			3 => "primary",
	);
?>
<div class="music-list">
	<?php foreach ($mediaList as $media):?>
	<?php 
		++$i;
		$name = $media['name']; 
	?>
	<div class="music-bit">
		<span class="label label-<?php echo isset($aryStyles[$i]) ? $aryStyles[$i] : "default"; ?>"><?php echo sprintf("%02s", $i) ?>.</span>
		<h3><a href="<?php echo Helper::makeUserLink($name, $value->_id) ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></h3>
		<div class="music-info info-top clearfix">
			<i class="fa fa-headphones"></i> Được nghe: <span><?php echo $media['view']; ?></span> lần
		</div>
	</div>
	 <?php endforeach;?>
</div>