<nav id="menu">
	<ul>
        <?php if(!$authentication): ?>
	        <li><form method="GET" action="timkiem.html">
	            <div class="input-group" style="margin: 0 5px;">
	              <input required="" class="form-control" placeholder="Tìm kiếm..." type="text" name="q" />
	              <span class="input-group-addon no-border"><button type="submit" class="btn btn-xs"><i class="fa fa-search text-muted"></i></button></span>
	            </div>
	            <p></p>
	            </form>
	        </li>
        <?php else :?>
	        <li class="userinfo" style="clear: both;">
	            <p><a href="<?php echo Helper::makeUserLink($userData['username'], $userId)?>"><img src="<?php echo strlen($userData['priavatar']) <= 0 ? " /wap/images/01.png" : $userData['priavatar']; ?>" class="imgavatar" /></a></p>
	            <p><a href="<?php echo Helper::makeUserLink($userData['username'], $userId)?>"><?php echo $userData['name']; ?></a></p>
	        </li>
        <?php endif; ?>
			<li><a href="/"><i class="fa fa-home"></i> Trang chủ</a></li>
        <?php if(!$authentication):?>
        	<li><a href="/dang-nhap"><i class="fa fa-user"></i> Tài khoản</a></li>
        <?php else: ?>
       		<li><a href="/tim-kiem"><i class="fa fa-search"></i> Tìm kiếm</a></li>
        <?php endif; ?>
		<li><a href="/bang-xep-hang-audio-w" title="Top Nhạc Sàn"><i class="fa fa-headphones"></i> Top Nhạc Sàn</a></li>
        <li><a href="/nguoi-dung-binh-chon-audio-w" title="Top Nhạc Sàn"><i class="fa fa-check"></i> Top Đề Cử</a></li>
        <li><a href="/bang-xep-hang-video-w" title="Top Video"><i class="fa fa-camera"></i> Top Video</a></li>
        <?php 
        	$viewCategory = ViewCategory::find(array(
        			"conditions" => array(
        					"position" => "sidebar"
        			),
        			"fields" => array("category"),
        			"sort" => array("sort" => 1)
        	));
        	
        	if (count($viewCategory)){
        		$viewCategoryIds = array();
        		foreach ($viewCategory as $value){
        			$viewCategoryIds[] = $value->category;
        		}
        	
	        	if (count($viewCategoryIds)){
	        		$categories = Category::find(array(
	        				"conditions" => array(
	        						'_id' => array(
	        								'$in' => $viewCategoryIds
	        						),
	        						"status" => "1"
	        				),
	        				"fields" => array("name", "type"),
	        		));
	        		
	        		if (count($categories)){
		        		$aryIcon = Helper::$aryMediaIcons;
		        		/* $categoryIds = array();
		        		foreach ($categories as $value){
		        			$categoryIds[] = $value->_id;
		        		}
		        		
		        		$categoryChildList = array();
		        		if (count($categoryIds)){
		        			
		        		} */
		        		
		        		foreach ($categories as $value){
		        		?>
			        		<li class="Selected">
								<a href="<?php echo Helper::urlGenerate($value->name, $value->_id, "category"); ?>" title="<?php echo $value->name; ?>"><i class="<?php echo $aryIcon[$value->type] ?>"></i> <?php echo $value->name; ?></a>
								<ul>
					                <?php 
					                	$categoryChild = Category::find(array(
					                			"conditions" => array(
					                					"parentid" => $value->_id,
					                					"status" => "1"
					                			),
					                			"fields" => array("name", "type"),
					                			"skip" => 0,
					                			"limit" => 10,
					                			"sort" => array("sort" => 1)
					                	));
					                	
					                	if (count($categoryChild)){
					                		foreach ($categoryChild as $child){
					                ?>
										<li><a href="<?php echo Helper::urlGenerate($child->name, $child->_id, "category") ?>" title="<?php echo $child->name; ?>"><?php echo $child->name; ?></a></li>
									<?php 
					                		}
					                	}
									?>
								</ul>
							</li>
		        		<?php 
		        		}
	        		}
	        	}
        	}
                ?>
		
        <li class="Selected">
			<a href="/album-moi" title="Album mới"><i class="fa fa-bars"></i> Album</a>
        <ul>
        <?php
            $albums = Album::find(array(
            		"distinct" => "category",
            		"fields" => array("category")
            ));
            
            if (count($albums)){
	            $albumCategoryIds = array();
	            foreach ($albums as $value){
	            	$albumCategoryIds[] = $value->_id;
	            }
	            
	            if (count($albumCategoryIds)){
	            	$albumCategories = Category::find(array(
	            			"conditions" => array(
	            					"_id" => array(
	            							'$in' => $albumCategoryIds
	            					),
	            					"status" => "1"
	            			),
	            			"fields" => array("name"),
	            			"skip" => 0,
	            			"limit" => 10,
	            			"sort" => array(
	            					"sort" => 1
	            			)
	            	));
	            	
	            	if (count($albumCategories)){
	            		foreach ($albumCategories as $value){
	            			?>
	            			<li><a href="<?php echo Helper::urlGenerate($value->name, $value->_id, $value->type); ?>" title="<?php echo $value->name; ?>"><?php echo $value->name; ?></a></li>
	            			<?php 
	            		}
	            	}
	            }
            }
        ?>
        </ul>
        </li>
        <?php
            $playList = PlayList::find(array(
            		"distinct" => "category",
            		"fields" => array("category")
            ));
            
            if (count($playList)){
	            $playlistCategoryIds = array();
	            foreach ($playList as $value){
	            	$playlistCategoryIds[] = $value->_id;
	            }
	            
	            if (count($playlistCategoryIds)){
	            	$playlistCategories = Category::find(array(
	            			"conditions" => array(
	            					"_id" => array(
	            							'$in' => $playlistCategoryIds
	            					),
	            					"status" => "1"
	            			),
	            			"fields" => array("name"),
	            			"skip" => 0,
	            			"limit" => 10,
	            			"sort" => array(
	            					"sort" => 1
	            			)
	            	));
	            	
	            	if (count($playlistCategories)){
	            		foreach ($playlistCategories as $value){
	            			?>
	            			<li><a href="<?php echo Helper::urlGenerate($value->name, $value->_id, $value->type); ?>" title="<?php echo $value->name; ?>"><?php echo $value->name; ?></a></li>
	            			<?php 
	            		}
	            	}
	            }
            }
        ?>
	</ul>
</nav>