<?php 
	$mediaId = $media->_id; 
	$mediaName = $media->name;
?>
<div class="col-lg-12">
	<div class="music-info">
			<h1><?php echo $mediaName ?></h1>
	</div>
	<div class="center bold"><a data-toggle="modal" data-target="#errorModal" href="javascript:void(0);">Nếu ko nghe được nhạc hãy click vào đây</a></div>
	<!-- Modal Error -->
	<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="errorModalLabel">Bạn không nghe được nhạc ?</h4>
		  </div>
		  <div class="modal-body">
			<p class="bold">Các lí do bạn không nghe được nhạc:</p>
			<ol>
				<li>Hãy đợi hệ thống load hết comment facebook rồi bấm play là được.</li>
				<li>Link bài hát của bài đó bị die - lúc đó hãy sử dụng nút báo cáo trong mỗi bài.</li>
				<li>Bạn đang sử dụng hệ điều hành iOS cũ (website chỉ hỗ trợ iOS 7.0 trở lên).</li>
				<li>Bài hát đó chưa được cập nhật link cho hệ điều hành iOS (iOS sẽ chạy link nhạc riêng, lúc đó hãy bấm vào nút yêu cầu cập nhật)</li>
				<li>Hãy sử dụng wifi để trải nghiệm nghe nhạc nhanh &amp; tốt nhất.</li>
			</ol>
			<div class="text-success">Nếu phát hiện lỗi của website, xin vui lòng gửi mail vào địa chỉ: <span class="text-primary"><a href="mailto:datleminh.93@gmail.com">datleminh.93@gmail.com</a></span> hoặc tài khoản Facebook: <span class="text-primary"><a href="https://www.facebook.com/kensei9x">www.facebook.com/kensei9x</a></span><br />Xin cảm ơn !</div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
		  </div>
		</div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	<div class="music-player">
		
		
		<div class="ios-player center">
			<p id="showloadding">Bấm play và chờ trình duyệt tải nhạc</p>
			<audio  autoplay loop preload="auto" autobuffer style="width:100%;">
			</audio>
		</div>
		<!-- Anh Viet Update 29-04-2014 -->
		<script src="/wap/plugin/audiojs/audiojs/audio.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			// Setup the player to autoplay the next track
			var a = audiojs.createAll({
				trackEnded: function () {
				},
				createPlayer: {
					markup: '\
				  <div class="play-pause"> \
					<p class="play" ><i onclick="wtf()" class="fa fa-play"></i></p> \
					<p class="pause"><i class="fa fa-pause"></i></p> \
					<p class="loading"><i class="fa fa-stop"></i></p> \
					<p class="error"><i class="fa fa-eject"></i></p> \
				  </div> \
				  <div class="time"> \
					  <em class="played">00:00</em>/<strong class="duration">00:00</strong> \
				  </div> \
				  <div class="error-message"></div>\
				  <div class="scrubber"> \
					<div class="progress"></div> \
					<div class="loaded"></div> \
				  </div>',
					playPauseClass: 'play-pause',
					scrubberClass: 'scrubber',
					progressClass: 'progress',
					loaderClass: 'loaded',
					timeClass: 'time',
					durationClass: 'duration',
					playedClass: 'played',
					errorMessageClass: 'error-message',
					playingClass: 'playing',
					//loadingClass: 'loading',
					errorClass: 'error',
					settings: {
						css: '.audiojs{width:100%}'
					}
				}
			});
	
			// Load in the first track
			var audio = a[0];
			first = '<?php echo Helper::switchlink($media->link) ?>';
			audio.load(first);
			
		</script>
		<!-- End VietNH -->
					
			  
		<p class="center bold text-success">Hãy dùng trình duyệt của bạn vào trực tiếp <a href="/" title="<?php echo $sitename; ?>"><?php echo $sitename; ?></a>  để khi khóa máy nhạc ko bị tắt !</p>
		
		<p></p>
		
		<div class="music-info">
			<div class="song-info">
				<ul>
					<li><i class="fa fa-headphones"></i> Lượt nghe: <span><?php echo $media->view ?></span></li>
					<li><i class="fa fa-download"></i> Lượt tải: <span><?php echo $media->download ?></span></li>
					<li><i class="fa fa-thumbs-up"></i> Like: <span><?php echo $media->liked ?></span> / Dislike: <span>0</span></li>
					<li><i class="fa fa-calendar"></i> Đăng ngày: <span><?php echo date("d-m-Y",$media->datecreate) ?></span></li>
					<li><i class="fa fa-music"></i> Thể loại:
						<?php 
	                    	$lastCategory = array_pop($category);
	                    ?>
	                    <?php foreach ($category as $value):?>
						<a href="<?php echo Helper::makeComposerLink($value->name, $value->_id)?>" title="<?php echo $value->name ?>"><?php echo $value->name; ?></a>, 
						<?php endforeach;?>
						<a href="<?php echo Helper::makeComposerLink($lastCategory->name, $lastCategory->_id)?>" title="<?php echo $lastCategory->name?>"><?php echo $lastCategory->name?></a>
					</li>
					<li><i class="fa fa-list"></i> Album: 
					<?php if ($albumInfo->_id): ?>
					<a href="#"><?php echo $albumInfo->name ?></a>
					<?php else: ?>
					Đang cập nhật
					<?php endif;?>
					</li>
					<li><i class="fa fa-users"></i> DJ: 
					<?php 
						if(count($media->singer) > 0){
						$singerList = $media->singer;
						foreach($singerList as $value){
					?>
					<a href="#"><?php echo $value->name ?></a>, 
					<?php } 
						} else echo "Đang cập nhật";
					?>
					</li>
				</ul>
			</div>
			<div class="user-avatar">
				<a href="<?php echo Helper::makeUserLink($user-> name, $user->_id); ?>" title="<?php echo $user-> name ?>"><img width="75" height="100" class="imgavatar_med" src="<?php echo $user->priavatar; ?>" /></a>
				<h4><a href="<?php echo Helper::makeUserLink($user->name ,$user->_id); ?>" title="<?php echo $user->name; ?>"><?php echo $user->name ?></a></h4>
			</div>
		</div>
		<div style="clear: both;"></div>
		
		<div class="btn-group btn-group-justified">  
		  <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#downloadModal" title="Tải về máy"><i class="fa fa-download"></i> Tải về</a>
		  <a class="btn btn-default btn-sm" href="javascript:void(0);" title="Báo cáo Spam" onclick="errorArticle(<?php echo $mediaId ?>);"><i class="fa fa-exclamation-circle"></i> Spam</a>
		  <a class="btn btn-default btn-sm" href="javascript:void(0);" title="Đề cử" onclick="nomination(<?php echo $mediaId ?>);"><i class="fa fa-check"></i> Đề cử</a>
		  <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal" title="Chia sẻ"><i class="fa fa-link"></i> Chia sẻ</a>
		</div>
		
		<!-- Modal Update Link iOS -->
		<div class="modal fade" id="updateLinkModal" tabindex="-1" role="dialog" aria-labelledby="updateLinkModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
			<div class="modal-content">
			  <div class="modal-body">
				<p class="text-success bold">Yêu cầu cập nhật link nghe trên iOS cho bài này đã được gửi thành công !</p>
				Vì để nghe được trên iOS, hệ thống phải sử dụng đường truyền riêng nên bạn hãy đợi BQT upload &amp; cập nhật nhé ! 
			  </div>
			  <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
			  </div>
			</div>
		  </div>
		</div>
		
		<!-- Modal Share -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
			<div class="modal-content">
			  <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Chia sẻ</h4>
			  </div>
			  <div class="modal-body">
				<p class="bold"><?php echo DOMAIN . Helper::urlGenerate($mediaName, $mediaId, "audio") ?></p>
				<p><a class="btn btn-primary btn-sm" href="http://m.facebook.com/sharer.php?u=<?php echo DOMAIN . Helper::urlGenerate($mediaName, $mediaId, "audio") ?>" target="_blank"><i class="fa fa-facebook-square"></i> Chia sẻ bài hát này lên Facebook</a></p>
				<p><a class="btn btn-danger btn-sm" href="http://plus.google.com/share?url=<?php echo DOMAIN . Helper::urlGenerate($mediaName, $mediaId, "audio") ?>" target="_blank"><i class="fa fa-google-plus-square"></i> Chia sẻ bài hát này lên Google Plus</a></p>
			  </div>
			  <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
			  </div>
			</div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
		
		<!-- Modal Download -->
		<div class="modal fade" id="downloadModal" tabindex="-1" role="dialog" aria-labelledby="downloadModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
			<div class="modal-content">
			  <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="downloadModalLabel">Tải bài hát về máy</h4>
			  </div>
			  <div class="modal-body">
				<p class="bold"><?php echo $mediaName ?></p>
				<p><a class="btn btn-primary btn-sm" href="<?php echo Helper::switchlink($media->link) ?>" target="_blank"><i class="fa fa-cloud-download"></i> Tải bản nén m4a</a></p>
				<p><a class="btn btn-danger btn-sm" href="<?php echo $media->link ?>" target="_blank"><i class="fa fa-download"></i> Tải bản Full 320kbps</a></p>
			  </div>
			  <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
			  </div>
			</div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
		
	</div>
	
	<div class="music-tracklist">
		<h4 class="block-title"><i class="fa fa-info-circle"></i> Thông tin bài hát:</h4>
		<div id="track-list" class="">
		<p>- Title: <?php echo $mediaName ?><br /></p>
		<?php echo $lyric=isset($media->lyric) ? $media->lyric : "Thông tin đang được cập nhật"; ?>
		<p class="seo no-display">Bản mix 
		<a title="<?php echo $mediaName ?>" href="<?php echo Helper::makeUserLink($user->name, $user->_id) ?>"><?php echo $mediaName ?></a> 
		do DJ <a title="<?php echo $user->name ?>" href="<?php echo Helper::makeUserLink($user->name, $user->_id) ?>"><?php echo $user->name ?></a> 
		Remix, trình bày bởi nhiều nghệ sĩ. Thuộc thể loại  - 
		<a href="<?php echo Helper::urlGenerate($category->name, $category->_id, "category") ?>" title="Xem the loai <?php echo $category->name ?>">
		<?php echo $category->name ?></a></p>
		<p class="seo no-display">Bạn có thể nghe nhạc nonstop chất lượng cao trực tuyến trên điện thoại di động, smartphone với thời gian dài và tốc độ cực nhanh, Tải bản mix nonstop <a title="<?php echo $mediaName ?>" href="<?php echo Helper::urlGenerate($mediaName, $mediaId, "audio") ?>"><?php echo $mediaName ?></a> - <a title="Tìm nhạc sàn, nonstop, những bản mix của nghệ sĩ <?php echo $user->name ?>" href="<?php echo Helper::makeUserLink($user->name, $user->_id) ?>"><?php echo $user->name ?></a> ngay trên Dj Chấm Không Đỡ Được Chấm Net. Về thể loại nhạc DJ chất lượng cao dành cho điện thoại di động, <?php echo $domain ?> tự hào là Website chia sẻ nhạc DJ, tải nhạc DJ lớn nhất, Những bản Mix do chính các DJ hàng đầu Việt Nam và các thành viên đóng góp.</p>
		</div>
		<a id="show-more-tracklist" class="btn text-warning btn-sm btn-block no-display" href="javascript:void(0);"><i class="fa fa-caret-down"></i> Xem thêm</a>
		<a id="show-less-tracklist" class="btn text-warning btn-sm btn-block" href="javascript:void(0);"><i class="fa fa-caret-up"></i> Thu gọn</a>
	</div>
</div>