<h5>Đăng nhập hệ thống</h5>
<form class="form-horizontal" action="" method="post" role="form">
   <div class="form-group">
      <div class="col-sm">
         <input type="text" class="form-control" id="username" name="username" placeholder="Tên đăng nhập">
      </div>
   </div>
   <div class="form-group">
      <div class="col-sm">
         <input type="password" class="form-control" id="password" name="password"  placeholder="Mật khẩu">
      </div>
   </div>   
   <div class="form-group">
      <div class="col-sm">
         <button type="submit" class="btn btn-default">Chấp nhận</button>
         Hoặc
         <a href="/dang-ky">Đăng ký mới</a>
      </div>
   </div>
</form>