<?php if (count($categoryList)):?>
<div id="accordion" class="panel-group top-area">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse">
                  <i class="fa fa-check"></i> Chuyên mục liên quan
                </a>
              </h4>
            </div>
            <div class="panel-collapse collapse" id="collapseTwo">
              <div class="panel-body">               
                <ul class="cat-list">
                        <?php  foreach($categoryList as $category): ?>
                        <?php 
	                        $icon = ($categoryType == 'video')
	                        	  ? 'fa-film'
                        		  : 'fa-music';
                        ?>
                        <li><a title="<?php echo $category->name ?>" href="<?php echo Helper::urlGenerate($category->name, $category->_id, "category") ?>"><i class="fa <?php echo $icon; ?>"></i><?php echo $category->name ?></a></li>
                        <?php endforeach; ?>
                    </ul>                 
              </div>
            </div>
          </div>  
</div>
<?php endif; ?>

<h5 class="center text-success">Danh sách <?php echo $categoryobj['name'] ?> - Trang <?php echo $p ?></h5>
<?php if ($categoryType == "audio"):?>
	<?php foreach ($mediaList as $media):?>
	<?php 
		$mediaName = $media->name;
		$mediaId = $media->_id;
	?>
	<div class="music-list">
		<div class="music-bit">
			<div class="music-icon"><i class="fa fa-music"></i></div>
			<h3><a href="<?php echo Helper::urlGenerate($mediaName, $mediaId, "audio"); ?>" title="<?php echo $mediaName; ?>"><?php echo $mediaName; ?></a></h3>
			<div class="music-info clearfix">
				<?php
					$user = User::findFirst(array(
							"conditions" => array(
									"_id" => $media->usercreate
							),
							"fields" => array("name", "username")               		
					));
				?>
				<i class="fa fa-user"></i> Đăng bởi: <a href="<?php echo Helper::makeUserLink($user->username, $user->_id)?>" title="<?php echo $user->name ?>"><?php echo $user->name ?></a> <span class="separator">/</span> <i class="fa fa-headphones"></i> <?php echo $media->view ?> <span class="separator">/</span> <i class="fa fa-download"></i> <?php echo $media->download ?> <?php if($media->ishot == 1) { ?> <span class="label label-danger label-margin">HOT</span> <?php } ?>  
			</div>
		</div>
	</div>
	<?php endforeach; ?>

<div class="btn-group btn-group-justified"><a class="btn btn-default" href="?p=<?php echo ($p-1==0)?1:$p-1 ?>" title="Trang trước"><i class="fa fa-angle-left"></i> Trang trước</a><a class="btn btn-default" href="?p=<?php echo $p+1 ?>" title="Trang sau"><i class="fa fa-angle-right"></i> Trang sau</a></div>        
<?php elseif ($categoryType == "video"):?>
	<div class="video-list no-margin">
		<?php foreach ($mediaList as $media):?>
		<?php 
			$mediaName = $media->name;
			$mediaId = $media->_id;
		?>
		<div class="video-bit">
			<a title="<?php echo $mediaName; ?>" href="<?php echo Helper::urlGenerate($mediaName, $mediaId) ?>"><img width="100" height="60" src="<?php echo $media->priavatar; ?>" alt="<?php echo $mediaName; ?>" /><i class="fa fa-youtube-play video-play-icon"></i></a>
			<h3><a href="<?php echo Helper::urlGenerate($mediaName, $mediaId, "video"); ?>" title="<?php echo $mediaName; ?>"><?php echo $mediaName; ?></a></h3>
			<div class="video-views"><i class="fa fa-eye"></i> Lượt xem: <?php echo $media->view; ?></div>
			<div class="clearfix"></div>
		</div>
		<?php endforeach;?>
	</div>
	<div class="btn-group btn-group-justified"><a class="btn btn-default" href="?p=<?php echo ($p - 1 == 0) ? 1 : $p - 1; ?>" title="Trang trước"><i class="fa fa-angle-left"></i> Trang trước</a><a class="btn btn-default" href="?p=<?php echo $p + 1 ?>" title="Trang sau"><i class="fa fa-angle-right"></i> Trang sau</a></div>
<?php endif;?>