<div id="content">
    <?php $this->partial("partial/breadCrumbs", array("data" => $categoryList[0])) ?>
    <?php 
    	$mediaId = $media->_id;
    	$mediaName = $media->name;
    ?>
    <div id="left-listen-column">
        <div class="column-bit">
            <div class="column-title music-cat"><?php echo $mediaName; ?></div>
            <div class="column-content no-padding">
                <div id="media-player">
                    <iframe width="100%" height="400" src="<?php echo Helper::switchlink($media->link)?>"></iframe>
                </div>

                <div class="video-simple-info">
                    <span class="left bold">
                        <i class="fa fa-user"></i> <a title="<?php echo $user->name; ?>" href="<?php echo Helper::makeUserLink($user->name, $user->_id)?>"><?php echo $user->name; ?></a>
                    </span>
                    <span class="right">
                        <i class="fa fa-calendar"></i>&nbsp;Ngày: <?php echo date("d-m-Y"); ?>&nbsp;
                        <i class="fa fa-thumbs-up"></i>&nbsp;<a id="like-count" href="javascript:showUserLike('<?php echo $media->_id; ?>', 'media')" rel="tooltip" data-original-title="Xem những ai thích bài này" title=""><?php echo $media->liked; ?></a>&nbsp;
                        <i class="fa fa-thumbs-down"></i>&nbsp;<a id="dislike-count" href="javascript:showUserDisLike('<?php echo $media->_id; ?>', 'media')" rel="tooltip" data-original-title="Xem những ai không thích bài này" title=""><?php echo $media->disliked; ?></a>&nbsp;
                        <i class="fa fa-eye"></i><?php echo $media->view; ?>
                    </span>
                    <div class="clear"></div>
                </div>

                <div id="track-list">
                    <div id="track-list-content" class="">
                        <p class="center video-tracklist"><?php echo $media->lyric; ?></p>
                    </div>
                    <div class="ex-col-btn">
                        <a id="show-more-songtracklist" class="show-tracklist no-display" href="javascript:void(0);"><b>Ấn</b> xem toàn bộ</a>
                        <a id="show-less-songtracklist" class="show-tracklist" href="javascript:void(0);"><b>Ấn</b> thu gọn</a>
                    </div>
                    <div class="clear"></div>
                    
                    <?php if (count($tagList)):?>
	                <div class="seperator-line1 clearfix"></div>
					<div class="seperator-line2"></div>
					<div class="mediainfo-padding">
					    <b><i class="fa fa-tags"></i> Tags:</b>
					    <div class="tag-cloud" style="overflow: hidden; width: auto; height: auto;">
					        <ul>
					            <?php foreach ($tagList as $tag):?>
					            <li><a href="<?php echo $tag->link?>" title="<?php echo $tag->name?>" target="_blank"><span></span><?php echo $tag->name?></a></li>
					            <?php endforeach;?>
					        </ul>
					    </div>
					</div>
					<?php endif;?>
					
                </div>
                <?php $this->partial("partial/comment", array("data" => $media, "type" => 'video')) ?>

                <div class="related-article no-margin"><i class="icon-music"></i> Video liên quan</div>
                <div class="wrap-song-list">
                    <div class="song-list">
                        <?php foreach ($newAudioList as $value):?>
                        <?php 
                        	$id = $value->_id;
                        	$name = $value->name;
                        ?>
                        <div class="song-bit">
                            <span class="song-icon"><i class="fa fa-music"></i></span>
                            <div class="song-name"><h3><a href="<?php echo Helper::urlGenerate($name, $id, "video"); ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></h3></div>
                            <div class="add-to-playlist"><a onclick="showAddPlaylist(<?php echo $id; ?>)" href="javascript:void(0)" title="Thêm vào Playlist nhạc"></a></div>
                            <div class="song-listen"><?php echo $value->view; ?> lượt</div>
                        </div>
                        <?php endforeach;?>
                    </div>
                </div>
                
                <!-- bai hat lien quan -->
	            <input type="hidden" id="posterId" value="<?php echo $media->usercreate; ?>" />
				<input type="hidden" id="prevPage" value="0" />
				<input type="hidden" id="nextPage" value="2" />
				<div class="related-article no-margin">
					<span>
						<i class="fa fa-headphones"></i>&nbsp; <?php echo $aryMediaTitles[$media->type]?> cùng người đăng &nbsp; 
						<span class="same-article-span">
							<a class="btn-prev-sameAudio" style="display: none;" onclick="moreArticle('prev','sameAudio','<?php echo $media->type?>');" href="javascript:void(0);">
								<i class="fa fa-chevron-left"></i>
							</a> 
							<a class="btn-next-sameAudio" onclick="moreArticle('next','sameAudio', '<?php echo $media->type?>');" href="javascript:void(0);">
								<i class="fa fa-chevron-right"></i>
							</a>
						</span>
					</span>
					<span class="same-poster">
					<i class="fa fa-music"></i>&nbsp; <?php echo $aryMediaRelatedTitles[$media->type]?> &nbsp; 
						<a class="btn-prev-unListen" style="display: none;" onclick="moreArticle('prev','unListen','<?php echo $media->type?>');" href="javascript:void(0);">
							<i class="fa fa-chevron-left"></i>
						</a> 
						<a class="btn-next-unListen" onclick="moreArticle('next','unListen', '<?php echo $media->type?>');" href="javascript:void(0);">
							<i class="fa fa-chevron-right"></i>
						</a>
					</span>
				</div>
				<div class="wrap-song-list clearfix">
				    <div class="song-list article-song-list left sameAudio">
				        <?php foreach ($userMediaList as $value):?>
				        <div class="song-bit">
				            <span class="song-icon"><i class="fa <?php echo $aryMediaIcons[$value->type]?>"></i></span>
				            <div class="song-name"><h3><a href="<?php echo Helper::urlGenerate($value->name, $value->_id, $value->type);?>" title="<?php echo $value->name; ?>"><?php echo $value->name; ?></a></h3></div>
				        </div>
				        <?php endforeach;?>
				    </div>
				
				    <div class="song-list article-song-list left unListen">
				        <?php foreach ($unListenList as $value):?>
				        <div class="song-bit">
				            <span class="song-icon"><i class="fa <?php echo $aryMediaIcons[$value->type]?>"></i></span>
				            <div class="song-name"><h3><a href="<?php echo Helper::urlGenerate($value->name, $value->_id, $value->type);?>" title="<?php echo $value->name; ?>"><?php echo $value->name; ?></a></h3></div>
				        </div>
				        <?php endforeach;?>
				    </div>
				
				</div>

            </div>
        </div>

    </div>

    <div id="right-listen-column">
        <div class="column-bit">
            <div class="column-title"><i class="icon-info"></i> Thao tác</div>
            <div class="column-content center">
                <p></p>
                <p>
                    <?php if ($authentication):?>
                    <a href="javascript:void(0);" onclick="javascript:likearticle(<?php echo $mediaId; ?>)" class="btn btn-mini" data-original-title="Thích bài này" title=""><i class="fa fa-thumbs-up"></i> Thích</a>
                    <a href="javascript:void(0);" onclick="javascript:dislikearticle(<?php echo $mediaId; ?>)" class="btn btn-mini" data-original-title="Không thích bài này" title=""><i class="fa fa-thumbs-down"></i> Không thích</a>
                    <?php else: ?>
                    <a href="javascript:void(0);" onclick="not_login();" class="btn btn-mini" href="javascript:void(0);"><i class="fa fa-thumbs-up"></i> Thích</a>
                    <a href="javascript:void(0);" onclick="not_login();" class="btn btn-mini"><i class="fa fa-thumbs-down"></i> Không thích</a>
                    <?php endif;?>
                </p>
                <p>
                    <a  onclick="showAddPlaylist(<?php echo $mediaId; ?>)" href="javascript:void(0)" class="btn btn-mini btn-success"><i class="fa fa-plus"></i> Thêm vào Playlist</a>

                    <a href="<?php echo Helper::makeDownloadLink($mediaName, $mediaId); ?>" class="btn btn-mini btn-info"><i class="fa fa-download"></i> Tải về máy</a>
                </p>
                <p>
                    <button title="" rel="tooltip" class="btn btn-mini btn-danger" id="nomination-article" disabled="disabled" <?php if ($authentication): ?> onclick="nomination(<?php echo $mediaId; ?>)" <?php else : ?>onclick="not_login()" <?php endif; ?> data-original-title="Đề cử bài này lên danh sách bài hát hay - ko cần đăng nhập cũng có thể đề cử"><i class="fa fa-check"></i> Đề cử <span id="nomi-count"></span></button>
                    <a href="#shareCode" class="btn btn-mini" data-toggle="modal" role="button"><i class="fa fa-code"></i> Nhúng web</a>
                    <?php $this->partial("partial/embedPopup", array("type" => "video", "mediaId" => $mediaId)) ?>
                </p>
            </div>
        </div>

        <div class="column-bit">
            <div class="column-title"><i class="icon-folder-open"></i> Video liên quan</div>
            <div class="column-content">
                <div id="random-video-list">
                    <?php foreach ($newVideoList as $value):?>
                    <?php 
                    	$id = $value->_id;
                    	$name = $value->name;
                    ?>
                    <?php echo $value->ishot; ?>
                    <div class="video-bit">
                        <div class="video-thumb"><a href="<?php echo Helper::urlGenerate($name, $id, $value->type); ?>" title="<?php echo $name; ?>"><img src="<?php echo $value->priavatar; ?>" alt="<?php echo $name; ?>" /><div class="play-video-icon"></div></a></div>
                        <div class="video-title"><h3><a href="<?php echo Helper::urlGenerate($name, $id, $value->type); ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></h3></div>
                    </div>
                    <?php endforeach;?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
<?php $this->partial("partial/addToPlayList") ?>
<?php $this->partial("partial/userLikeList", array("mediaId" => $media->_id, "type" => "video")) ?>