<?php $this->partial("partial/breadCrumbs", array("categorys" => $category)) ?>
<div id="left-listen-column">
    <div class="column-bit">
        <div class="column-title music-cat">Tuyển tập album <?php echo $title; ?></div>
        <div class="column-content">
            <div class="break-list-line"></div>
            <div id="list-news-cat">
                 <?php if (count($albumList)):?>
                    <?php foreach ($albumList as $album):?>
                    <?php 
                    	$albumName = $album->name;
                    	$albumUrl = Helper::urlGenerate($album->name, $album->_id, 'album');
                    ?>
                    <div class="news-bit">
                        <div class="news-cover">
                            <div class="img-cover">
                                <a title="<?php echo $albumName; ?>" href="<?php echo $albumUrl; ?>">
                                <img class="img162" width="162" height="162" alt="<?php echo $albumName; ?>" src="<?php echo $album->priavatar; ?>"/>
                                </a>
                            </div>
                        </div>
                        <div class="news-info">
                            <h3 class="news-name">
                                <a title="<?php echo $albumName; ?>" href="<?php echo $albumUrl; ?>"><?php echo $albumName; ?></a>
                            </h3>

                            <div class="news-profile">
                                <span class="news-view"><i class="fa fa-eye"></i> <?php echo $album->view; ?></span>
                                <span class="news-date"><i class="fa fa-calendar"></i> </span>
                                <span class="news-like"><i class="fa fa-thumbs-up"></i> <?php echo $album->liked; ?></span>
                            </div>
                            <div class="news-desc"><?php echo $albumName; ?></div>
                        </div>
                        <br class="clear"/>
                    </div>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
            <div class="clear"></div>
            <div class="break-list-line1"></div>

            <?php $this->partial("partial/paging", array("totalNumber" => $mediaCount, "pageTotal" => $pageTotal)) ?>
        </div>

    </div>
</div>
<?php $this->partial("partial/rightSlideBar") ?>